// Livros da Bíblia em português (NWT)
export const BIBLE_BOOKS = [
  // Hebraico-Aramaico
  { id: 'GEN', name: 'Gênesis', chapters: 50, testament: 'AT' },
  { id: 'EXO', name: 'Êxodo', chapters: 40, testament: 'AT' },
  { id: 'LEV', name: 'Levítico', chapters: 27, testament: 'AT' },
  { id: 'NUM', name: 'Números', chapters: 36, testament: 'AT' },
  { id: 'DEU', name: 'Deuteronômio', chapters: 34, testament: 'AT' },
  { id: 'JOS', name: 'Josué', chapters: 24, testament: 'AT' },
  { id: 'JUD', name: 'Juízes', chapters: 21, testament: 'AT' },
  { id: 'RUT', name: 'Rute', chapters: 4, testament: 'AT' },
  { id: '1SA', name: '1 Samuel', chapters: 31, testament: 'AT' },
  { id: '2SA', name: '2 Samuel', chapters: 24, testament: 'AT' },
  { id: '1RE', name: '1 Reis', chapters: 22, testament: 'AT' },
  { id: '2RE', name: '2 Reis', chapters: 25, testament: 'AT' },
  { id: '1CR', name: '1 Crônicas', chapters: 29, testament: 'AT' },
  { id: '2CR', name: '2 Crônicas', chapters: 36, testament: 'AT' },
  { id: 'ESD', name: 'Esdras', chapters: 10, testament: 'AT' },
  { id: 'NEE', name: 'Neemias', chapters: 13, testament: 'AT' },
  { id: 'EST', name: 'Ester', chapters: 10, testament: 'AT' },
  { id: 'JOB', name: 'Jó', chapters: 42, testament: 'AT' },
  { id: 'SAL', name: 'Salmos', chapters: 150, testament: 'AT' },
  { id: 'PRO', name: 'Provérbios', chapters: 31, testament: 'AT' },
  { id: 'ECL', name: 'Eclesiastes', chapters: 12, testament: 'AT' },
  { id: 'CAN', name: 'Cântico dos Cânticos', chapters: 8, testament: 'AT' },
  { id: 'ISA', name: 'Isaías', chapters: 66, testament: 'AT' },
  { id: 'JER', name: 'Jeremias', chapters: 52, testament: 'AT' },
  { id: 'LAM', name: 'Lamentações', chapters: 5, testament: 'AT' },
  { id: 'EZE', name: 'Ezequiel', chapters: 48, testament: 'AT' },
  { id: 'DAN', name: 'Daniel', chapters: 12, testament: 'AT' },
  { id: 'OSE', name: 'Oseias', chapters: 14, testament: 'AT' },
  { id: 'JOE', name: 'Joel', chapters: 3, testament: 'AT' },
  { id: 'AMO', name: 'Amós', chapters: 9, testament: 'AT' },
  { id: 'OBA', name: 'Obadias', chapters: 1, testament: 'AT' },
  { id: 'JON', name: 'Jonas', chapters: 4, testament: 'AT' },
  { id: 'MIQ', name: 'Miquéias', chapters: 7, testament: 'AT' },
  { id: 'NAU', name: 'Naum', chapters: 3, testament: 'AT' },
  { id: 'HAB', name: 'Habacuque', chapters: 3, testament: 'AT' },
  { id: 'SOF', name: 'Sofonias', chapters: 3, testament: 'AT' },
  { id: 'AGA', name: 'Ageu', chapters: 2, testament: 'AT' },
  { id: 'ZAC', name: 'Zacarias', chapters: 14, testament: 'AT' },
  { id: 'MAL', name: 'Malaquias', chapters: 4, testament: 'AT' },
  // Grego
  { id: 'MAT', name: 'Mateus', chapters: 28, testament: 'NT' },
  { id: 'MAR', name: 'Marcos', chapters: 16, testament: 'NT' },
  { id: 'LUC', name: 'Lucas', chapters: 24, testament: 'NT' },
  { id: 'JOA', name: 'João', chapters: 21, testament: 'NT' },
  { id: 'ATO', name: 'Atos', chapters: 28, testament: 'NT' },
  { id: 'ROM', name: 'Romanos', chapters: 16, testament: 'NT' },
  { id: '1CO', name: '1 Coríntios', chapters: 16, testament: 'NT' },
  { id: '2CO', name: '2 Coríntios', chapters: 13, testament: 'NT' },
  { id: 'GAL', name: 'Gálatas', chapters: 6, testament: 'NT' },
  { id: 'EFE', name: 'Efésios', chapters: 6, testament: 'NT' },
  { id: 'FIL', name: 'Filipenses', chapters: 4, testament: 'NT' },
  { id: 'COL', name: 'Colossenses', chapters: 4, testament: 'NT' },
  { id: '1TE', name: '1 Tessalonicenses', chapters: 5, testament: 'NT' },
  { id: '2TE', name: '2 Tessalonicenses', chapters: 3, testament: 'NT' },
  { id: '1TI', name: '1 Timóteo', chapters: 6, testament: 'NT' },
  { id: '2TI', name: '2 Timóteo', chapters: 4, testament: 'NT' },
  { id: 'TIT', name: 'Tito', chapters: 3, testament: 'NT' },
  { id: 'FLM', name: 'Filemom', chapters: 1, testament: 'NT' },
  { id: 'HEB', name: 'Hebreus', chapters: 13, testament: 'NT' },
  { id: 'TIA', name: 'Tiago', chapters: 5, testament: 'NT' },
  { id: '1PE', name: '1 Pedro', chapters: 5, testament: 'NT' },
  { id: '2PE', name: '2 Pedro', chapters: 3, testament: 'NT' },
  { id: '1JO', name: '1 João', chapters: 5, testament: 'NT' },
  { id: '2JO', name: '2 João', chapters: 1, testament: 'NT' },
  { id: '3JO', name: '3 João', chapters: 1, testament: 'NT' },
  { id: 'JUD2', name: 'Judas', chapters: 1, testament: 'NT' },
  { id: 'APO', name: 'Apocalipse', chapters: 22, testament: 'NT' },
]

// Abreviações aceitas para autocomplete de versículos
export const BOOK_ALIASES: Record<string, string> = {
  'gn': 'GEN', 'gen': 'GEN', 'gênesis': 'GEN', 'genesis': 'GEN',
  'ex': 'EXO', 'êxodo': 'EXO', 'exodo': 'EXO',
  'lv': 'LEV', 'levítico': 'LEV', 'levitico': 'LEV',
  'nm': 'NUM', 'números': 'NUM', 'numeros': 'NUM',
  'dt': 'DEU', 'deuteronômio': 'DEU', 'deuteronomio': 'DEU',
  'js': 'JOS', 'josué': 'JOS', 'josue': 'JOS',
  'jz': 'JUD', 'juízes': 'JUD', 'juizes': 'JUD',
  'rt': 'RUT', 'rute': 'RUT',
  '1sm': '1SA', '1samuel': '1SA', '1 samuel': '1SA',
  '2sm': '2SA', '2samuel': '2SA', '2 samuel': '2SA',
  '1rs': '1RE', '1reis': '1RE', '1 reis': '1RE',
  '2rs': '2RE', '2reis': '2RE', '2 reis': '2RE',
  'sl': 'SAL', 'salmos': 'SAL', 'salmo': 'SAL',
  'pv': 'PRO', 'provérbios': 'PRO', 'proverbios': 'PRO',
  'ec': 'ECL', 'eclesiastes': 'ECL',
  'is': 'ISA', 'isaías': 'ISA', 'isaias': 'ISA',
  'jr': 'JER', 'jeremias': 'JER',
  'ez': 'EZE', 'ezequiel': 'EZE',
  'dn': 'DAN', 'daniel': 'DAN',
  'mt': 'MAT', 'mateus': 'MAT',
  'mc': 'MAR', 'marcos': 'MAR',
  'lc': 'LUC', 'lucas': 'LUC',
  'jo': 'JOA', 'joão': 'JOA', 'joao': 'JOA',
  'at': 'ATO', 'atos': 'ATO',
  'rm': 'ROM', 'romanos': 'ROM',
  '1co': '1CO', '1coríntios': '1CO', '1corintios': '1CO',
  '2co': '2CO', '2coríntios': '2CO', '2corintios': '2CO',
  'gl': 'GAL', 'gálatas': 'GAL', 'galatas': 'GAL',
  'ef': 'EFE', 'efésios': 'EFE', 'efesios': 'EFE',
  'fp': 'FIL', 'filipenses': 'FIL',
  'cl': 'COL', 'colossenses': 'COL',
  '1ts': '1TE', '1tessalonicenses': '1TE',
  '2ts': '2TE', '2tessalonicenses': '2TE',
  '1tm': '1TI', '1timóteo': '1TI', '1timoteo': '1TI',
  '2tm': '2TI', '2timóteo': '2TI', '2timoteo': '2TI',
  'tt': 'TIT', 'tito': 'TIT',
  'hb': 'HEB', 'hebreus': 'HEB',
  'tg': 'TIA', 'tiago': 'TIA',
  '1pe': '1PE', '1pedro': '1PE', '1 pedro': '1PE',
  '2pe': '2PE', '2pedro': '2PE', '2 pedro': '2PE',
  '1jo': '1JO', '1joão': '1JO', '1joao': '1JO',
  '2jo': '2JO', '3jo': '3JO',
  'jd': 'JUD2', 'judas': 'JUD2',
  'ap': 'APO', 'apocalipse': 'APO',
}

export function findBookByAlias(name: string): typeof BIBLE_BOOKS[0] | undefined {
  const lower = name.toLowerCase().trim()
  const id = BOOK_ALIASES[lower]
  return id ? BIBLE_BOOKS.find(b => b.id === id) : BIBLE_BOOKS.find(b => b.name.toLowerCase() === lower)
}
